### ISSUE TITLE
Empty Playlists

### ISSUE THREAD

**Issue by neoflex** [akezeke/spotyxbmc2#1]
My spotify playlists are desperatly empty. I can see my list of playlists, but when I try to enter in one of them, there is no songs inside. Nothing special in the log file.

**Comment by akezeke** [comment]
Yes this is a known issue (for some, I dont have the problem very often). There seems to be some kind of problem in the lib, libspotify says that the playlist is loaded, the name can be resolved but it is reporting the playlist as empty... I will take a closer look at this again in a couple of days.

**Comment by akezeke** [comment]
And if you try to do something else (like browse toplists) before checking on the playlists it seems to work better.

**Comment by akezeke** [comment]
Neoplex, can you please try now? Here it works everytime now.

**Comment by neoflex** [comment]
Thanks you for looking at this. I am at work right now, will test tonight and keep you informed ;)

**Comment by neoflex** [comment]
thanks a lot, now my playlists are never empties!

just still a bug with some of my playlists. I don't understand why but as soon as I open them, I can briefly see the tracks but XBMC just crash. 
Here is an example of such case: spotify:user:neoflex:playlist:2xE6ir3Cp9cK4cfRv0erUv
(sorry that's french kids songs :p)

There is no much information in the log file I think:

<code>
20:29:31 T:3016427328 M:3012321280   DEBUG:   ParentPath = [musicdb://spotify/menu/playlists/]
20:29:31 T:3016427328 M:3012321280   DEBUG: Spotifylog: loading playlist: 50
20:29:32 T:3016427328 M:3012321280   DEBUG: Album format left  = [%B]
20:29:32 T:3016427328 M:3012321280   DEBUG: Album format right = [%A]
20:29:32 T:3016427328 M:3012321280   DEBUG: Album format left  = [%B]
20:29:32 T:3016427328 M:3012321280   DEBUG: Album format right = [%A]
20:29:32 T:3016427328 M:3012321280   DEBUG: Album format left  = [%B]
20:29:32 T:3016427328 M:3012321280   DEBUG: Album format right = [%A]
20:29:32 T:3016427328 M:3012321280   DEBUG: Spotifylog: fetching thumb
20:29:32 T:3016427328 M:3012321280   DEBUG: Spotifylog: releasing thumb
20:29:32 T:3016427328 M:3012321280   DEBUG: Spotifylog: fetching thumb

 </code>

**Comment by akezeke** [comment]
I think it is fixed now, please try again!

Nice music in that playlist :)

**Comment by neoflex** [comment]
still crashing, but with more details in the log files :p

thanks anyway, tell me if I can help you somehow to solve this.

<code>
09:41:25 T:3016316736 M:2999345152   DEBUG: Spotifylog: releasing thumb
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb 2
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb 3
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb 4
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: releasing thumb
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb 2
09:41:25 T:3016316736 M:2999496704   DEBUG: Spotifylog: fetching thumb 3
</code>

**Comment by akezeke** [comment]
hm ok, it does not crash for me with your playlist now (it did before the fix) I'll see if I find something... I guess you already did but make sure you do a clean build.

**Comment by neoflex** [comment]
I didn't :/
sry, trying again.

when is a clean make necessary?

**Comment by neoflex** [comment]
still crashing, I'll try to debug myself because it will be difficult from your side if you can't reproduce the bug :/

**Comment by neoflex** [comment]
finally found something :)

in SpotifyInterface::requestThumb, I modified it to check the sp_image_create for errors.

<code>
    sp_image _spImage = sp_image_create(m_session, (byte_)imageId);
    <b>sp_error spError = sp_image_error(spImage);
    if (spError == SP_ERROR_OK)</b>
    {
      //ok there is one, so download it!
      m_noWaitingThumbs++;
      sp_image_add_load_callback(spImage, &cb_imageLoaded, pItem.get());
      return true;
    }
    <b>else{
        CLog::Log( LOGDEBUG, "error loading thumb %d",spError);
    }</b>
  }
</code>

In bold the modified part.
I get a bunch of errors 17, which corresponds to "SP_ERROR_IS_LOADING" regarding to api.h ;)

so now it doesn't crash, just not all thumbs are loaded the first time I enter a playlist ;)
I guess you didn't have the problem because your connection/or proc is better than mines.

**Comment by neoflex** [comment]
there is a sp_image_add_load_callback function, maybe it can be oen way to solve this ;)

**Comment by akezeke** [comment]
Well the function that is failing for you is the callback.

**Comment by neoflex** [comment]
oh, I realize what I did was kind of stupid, even if it solved my pb :p
I'll check the cb_imageLoaded function with sp_image_error().

**Comment by neoflex** [comment]
the call item->GetExtraInfo(); in cb_imageLoaded seems to cause the crash. I can't understand why, any idea of what I should do to figure out something?
